config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  resources :events, only: [:show, :index]
  resources :info_forms

  post "/" => 'info_forms#create'

  namespace :admin do
    resources :events, :packages
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :packages

	def difference
		today = Date.today

		start_date = starts_on.to_date

		if start_date > today
			difference = (start_date - today).to_i.to_s + " days"
		else
			difference = "The event has passed"
		end
	end
end

app/models/info_form.rb
class InfoForm < ActiveRecord::Base
end

app/models/package.rb
class Package < ActiveRecord::Base
	belongs_to :event
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /admin/events
  # GET /admin/events.json
  def index
    @events = Event.all
  end

  # GET /admin/events/1
  # GET /admin/events/1.json
  def show
  end

  # GET /admin/events/new
  def new
    @event = Event.new
  end

  # GET /admin/events/1/edit
  def edit
  end

  # POST /admin/events
  # POST /admin/events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to [:admin, @event], notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/events/1
  # PATCH/PUT /admin/events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to [:admin, @event], notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/events/1
  # DELETE /admin/events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to admin_events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :active, :starts_on, :ends_on)
    end
end

app/controllers/admin/packages_controller.rb
class Admin::PackagesController < ApplicationController
  before_action :set_package, only: [:show, :edit, :update, :destroy]

  # GET /admin/packages
  # GET /admin/packages.json
  def index
    @events = Event.all
    @packages = Package.all
  end

  # GET /admin/packages/1
  # GET /admin/packages/1.json
  def show
  end

  # GET /admin/packages/new
  def new
    @events = Event.all
    @package = Package.new
  end

  # GET /admin/packages/1/edit
  def edit
    @events = Event.all
  end

  # POST /admin/packages
  # POST /admin/packages.json
  def create
    @package = Package.new(package_params)

    respond_to do |format|
      if @package.save
        format.html { redirect_to [:admin, @package], notice: 'Package was successfully created.' }
        format.json { render action: 'show', status: :created, location: @package }
      else
        format.html { render action: 'new' }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/packages/1
  # PATCH/PUT /admin/packages/1.json
  def update
    respond_to do |format|
      if @package.update(package_params)
        format.html { redirect_to [:admin, @package], notice: 'Package was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/packages/1
  # DELETE /admin/packages/1.json
  def destroy
    @package.destroy
    respond_to do |format|
      format.html { redirect_to admin_packages_url, notice: 'Package was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_package
      @package = Package.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def package_params
      params.require(:package).permit(:name, :description, :event_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
    @event = Event.find params[:id]
    @packages = Package.where(event_id: @event.id)
    @package = Package.find params[:id] rescue nil
    @info_form = InfoForm.new
  end

  def index
    @events = Event.all.order("starts_on ASC").where(active: true)
  end
end

app/controllers/info_forms_controller.rb
class InfoFormsController < ApplicationController

  def create
    @info_form = InfoForm.new(info_form_params)

    respond_to do |format|
    	if @info_form.save
    		format.html { redirect_to root_url, notice: 'Information saved.' }
      end
    end
  end

  private

  def info_form_params
  	params.require(:info_form).permit(:first_name, :last_name, :email)
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/admin/packages_helper.rb
module Admin::PackagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/admin/events/_form.html.erb
<%= form_for([:admin, @event]) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :name %><br>
    <%= f.text_field :name %>
    </div>
  <div class="field">
      <%= f.label :active %><br>
    <%= f.check_box :active %>
    </div>
  <div class="field">
      <%= f.label :starts_on %><br>
    <%= f.datetime_select :starts_on %>
    </div>
  <div class="field">
      <%= f.label :ends_on %><br>
    <%= f.datetime_select :ends_on %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @event] %> |
<%= link_to 'Back', admin_events_path %>

app/views/admin/events/index.html.erb
<h1>Listing events</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th>Starts on</th>
      <th>Ends on</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.active %></td>
        <td><%= event.starts_on %></td>
        <td><%= event.ends_on %></td>
        <td><%= link_to 'Show', [:admin, event] %></td>
        <td><%= link_to 'Edit', edit_admin_event_path(event) %></td>
        <td><%= link_to 'Destroy', [:admin, event], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_admin_event_path %>

app/views/admin/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_events_path %>

app/views/admin/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @event.active %>
</p>

<p>
  <strong>Starts on:</strong>
  <%= @event.starts_on %>
</p>

<p>
  <strong>Ends on:</strong>
  <%= @event.ends_on %>
</p>

<%= link_to 'Edit', edit_admin_event_path(@event) %> |
<%= link_to 'Back', admin_events_path %>

app/views/events/_form.html.erb
<%= form_for(@info_form) do |f| %>
	<% if @info_form.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@info_form.errors.count, "error") %> prohibited your information from being sent:</h2>
			<ul>
				<% @info_form.errors.full_messages.each do |message| %>
			    		<li><%= message %></li>
			    	<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="field">
		<%= f.label :first_name %><br>
		<%= f.text_field :first_name %>
	</div>
	<div class="field">
		<%= f.label :last_name %><br>
		<%= f.text_field :last_name %>
	</div>
	<div class="field">
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</div>
	<div class="actions">
		<%= f.submit "Submit" %>
	</div>
<% end %>

app/views/events/index.html.erb
<div class="container">

  <div class="starter-template">
    <div class="row">
      <div class="col-lg-2">
        <%= image_tag 'cltSpartan.png', width: '150px', height: 'auto' %>
      </div>
      <div class="col-lg-10">
        <p class="lead text-left">Welcome to the home of the Carolina Spartans!  <br />
          We are excited to announce the 2016 MLS season is about to begin.  We hope to<br />
          continue from last year's winning debut season and come home with the Cup.  <br />
          Be sure to checkout our events page for upcoming games.</p>
      </div>
      </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <h2>AVAILABLE EVENTS</h2>
      <hr />
    </div>
    <div class="col-lg-12">
      <div class="row">
        <div class="col-lg-6">
          <table class="table">
            <tr>
              <th>Name</th>
              <th>Starting Date</th>
              <th>Days Until Start</th>
            </tr>
            <% @events.each do |event| %>
            <tr>
              <td>
                <%=link_to event.name, event%>
              </td>
              <td>
                <%=event.starts_on.strftime('%b %d %Y')%>
              </td>
              <td>
                <%= event.difference %>
              </td>
            </tr>
            <%end%>
          </table>
        </div>
        <div class="col-lg-6">
          <p>
            We are excited to bring you 4 events in 2016.  Events range from different soccer tournaments to children's camps.
            All of the events are family friendly and we are hoping to see you all out at the park.
          </p>
        </div>
      </div>
    </div>
  </div>
</div><!-- /.container -->

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="text-left" style="padding-bottom: 0px;">
        <%= image_tag 'cltSpartan.png', width: '150px', height: 'auto' %>
        <%=@event.name%>
      </h1>
    </div>
  </div>
  <hr style="margin-top: 0px;"/>
</div><!-- /.container -->
<div class="container">
  <div class="row">
    <div class="col-lg-8" style="border-right: 1px solid #cdcdcd;">
      <h2>PACKAGES</h2>
      <% @packages.each do |package| %>
          <h3><%= package.name %></h3>
          <p><%= package.description %></p>
      <% end %>
      <h4><%= "There are no packages for this event." if @packages.blank? %></h4>
    </div>
    <br />
    <div class="col-lg-4">
      <h2>CONTACT US</h2>
        <%= render 'form' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qea</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'CHARLOTTE SPARTANS', root_path, class: 'navbar-brand'%>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path%></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>
<%= notice %>
<%= yield %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>